# `rustfmt` internal settings
#
# emit_mode = "Files"
# make_backup = false

binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
color = "Auto"
combine_control_expr = false # better all around in our opinions
comment_width = 80 # changed
condense_wildcard_suffixes = true # changed
control_brace_style = "AlwaysSameLine"
disable_all_formatting = false
edition = "2018" # changed
empty_item_single_line = true
enum_discrim_align_threshold = 0
error_on_line_overflow = true # be more strict
error_on_unformatted = true # be more strict
fn_args_layout = "Tall"
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = true # changed
format_code_in_doc_comments = false
format_macro_bodies = true
format_macro_matchers = false
format_strings = false
hard_tabs = false
hide_parse_errors = false
ignore = []
imports_indent = "Block"
imports_layout = "Vertical" # makes editing quicker
inline_attribute_width = 0 # unchanged, for ease of editing
# license_template_path = "LICENSE_TEMPLATE" # changed
match_arm_blocks = true
match_block_trailing_comma = false
max_width = 90 # changed
merge_derives = true
merge_imports = true # changed
newline_style = "Unix" # changed, prevents `\r\n` being accidentally introduced
normalize_comments = true # no /* */ comments should be in master
normalize_doc_attributes = true # changed
overflow_delimited_expr = false
remove_nested_parens = true
reorder_impl_items = true # changed
reorder_imports = true
reorder_modules = true
report_fixme = "Always" # changed
report_todo = "Always" # changed
# required_version = "CARGO_PKG_VERSION"
skip_children = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 0
struct_lit_single_line = true
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = false # changed
type_punctuation_density = "Wide"
unstable_features = true # changed
use_field_init_shorthand = true # changed
use_small_heuristics = "Default"
use_try_shorthand = true # changed
version = "Two" # changed
where_single_line = false # unchanged, for ease of editing
wrap_comments = true # fits comments to the line
